### ISSUE TITLE
Create a new rule will overwrite an existed rule file

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#10]
https://github.com/bitsensor/elastalert-kibana-plugin/issues/91

**Comment by Karql** [comment]
I know that problem and I have it on my todo.

It is issue from https://github.com/bitsensor/elastalert
POST action is responsible for creating and editing rule | template

I would like to split it to POST  and PUT and also refactor models a bit but it will be a breaking change.
Before it I have to finish migration to swagger, migration to elastalert2 etc.
