### ISSUE TITLE
Are there any plans to release Elastalert plugins for kibana 7.14.1?

### ISSUE THREAD

**Issue by fabioformosa** [Karql/elastalert-kibana-plugin#12]
thank you for your effort in taking in charge the development of this plugin!
Do you have any plan to release a support for kibana 7.15.1

**Comment by Karql** [comment]
Hi!

I've just released version:
- 7.14.2
- 7.15.0
- 7.15.1

https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.4.0

btw. Have you tried https://github.com/Karql/elastalert2-server ?
I've add swagger support and IMO it is event better than this plugin 😉

Regards,
Mateusz
