### ISSUE TITLE
About the name

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#13]
Isn't it better to switch to elastalert2-kibana-plugin instead of elastalert-kibana-plugin?

**Comment by Karql** [comment]
For know this plugin support both version.
I don't see any benefits but only breaking changes.

Maybe when there will be other changes in the future.

**Comment by nsano-rururu** [comment]
If so, shouldn't the README be updated as follows?

Added Elast Alert Server link to Requirements
https://github.com/Karql/elastalert2-server/tree/release/4.0.x

and

Added Elast Alert Server Docker Images link to Installation
https://hub.docker.com/r/karql/elastalert

**Comment by Karql** [comment]
I've considered that but to avoid confusion readme point only to the latest version.
