### ISSUE TITLE
Missing correction when fixing with new kibana-plugin

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#17]
Forgot to correct the URL when clicking the github icon below
![キャプチャ](https://user-images.githubusercontent.com/22293449/148759596-943b2eff-b7c4-4806-9afe-92002c2d549f.PNG)

https://github.com/Karql/elastalert-kibana-plugin/blob/master/public/components/main/main.tsx#L74

current

```
'https://github.com/bitsensor/elastalert-kibana-plugin',
```

fix

```
'https://github.com/Karql/elastalert-kibana-plugin',
```

**Comment by Karql** [comment]
Thanks 👍
