### ISSUE TITLE
The URL in About on the top page is the address of the bitsensor. Forgot to erase it?

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#19]
It is in the red frame. I think it will be changed on the setting screen. Unless you are a maintainer, you cannot change it.
![キャプチャ](https://user-images.githubusercontent.com/22293449/148777450-4eb1e9e2-ffdf-4128-8b00-1a1a19556970.PNG)

**Comment by Karql** [comment]
Thank you for pointing it out.
I've removed it.
