### ISSUE TITLE
Forgot to erase the debug code during development?

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#20]
https://github.com/Karql/elastalert-kibana-plugin/blob/master/public/components/rules/editor/editor.tsx#L46

```
console.log(this.state);
```

https://github.com/Karql/elastalert-kibana-plugin/blob/master/server/routes/index.ts#L90

```
console.log(postParams);
```

**Comment by Karql** [comment]
Yes those two places are my fault.

There was one more.

I've removed all.
