### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by waleedsheyyab** [Karql/elastalert-kibana-plugin#21]
undefined - undefined
Cannot read properties of undefined (reading 'sort')
Appears on the gui plugin

**Comment by nsano-rururu** [comment]
I think you should write the following.

- version of kibana
- docker? .. Direct installation
- kibana configuration file

**Comment by waleedsheyyab** [comment]
Kibana V 7.11
docker image 
Kibana.yml
elasticsearch.username: "sdfvsd"
elasticsearch.password: "sdfsdf"

xpack.security.enabled: true

elasticsearch.hosts: ["https://localhost:9200"]



xpack.encryptedSavedObjects.encryptionKey: dfgbdfbdfbdfb
xpack.reporting.encryptionKey: cvbdfvdfbd
xpack.security.encryptionKey: 2dfvdfvdfvdfd

elasticsearch.ssl.certificateAuthorities: /etc/kibana/elasticsearch-ca.pem

elasticsearch.ssl.verificationMode: none
elastalertKibanaPlugin.serverSsl: false
elastalertKibanaPlugin.serverHost: localhost
elastalertKibanaPlugin.serverPort: 5601

**Comment by Karql** [comment]
`Sort` only appears here: 

https://github.com/Karql/elastalert-kibana-plugin/blob/ee5e71e50c061a7bbee674488c1f6cf466004864/public/components/rules/list/list.tsx#L65

What version of [elastalert2-server](https://github.com/Karql/elastalert2-server) do you have?
Check if there any logs from elastalert2-server.

**Comment by waleedsheyyab** [comment]
I'm using the latest image 
Here are the logs please find them below

ERROR:elastalert:Error finding recent pending alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [alert_time] in order to sort on') {'query': {'bool': {'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'filter': {'range': {'alert_time': {'from': '2022-01-16T11:20:56.705881Z', 'to': '2022-01-18T11:20:56.705912Z'}}}}}, 'sort': {'alert_time': {'order': 'asc'}}}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py", line 1740, in find_recent_pending_alerts
    res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/client/__init__.py", line 810, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/connection/http_requests.py", line 91, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [alert_time] in order to sort on')
INFO:elastalert:Background alerts thread 0 pending alerts sent at 2022-01-18 11:20 UTC
INFO:elastalert:Queried rule New country login from 2022-01-18 11:06 UTC to 2022-01-18 11:21 UTC: 0 / 0 hits
INFO:elastalert:Ran New country login from 2022-01-18 11:06 UTC to 2022-01-18 11:21 UTC: 0 query hits (0 already seen), 0 matches, 0 alerts sent
INFO:elastalert:New country login range 900

**Comment by Karql** [comment]
Are you sure that you use `elastalert2-server` not just `elastarlert2`?

From you log: `File "/usr/local/lib/python3.10/site-packages/elastalert/elastalert.py"`

But in `elastalert2-server`  python is in version 3.9: https://github.com/Karql/elastalert2-server/blob/8327d41b545ae3b3d2bbc6843f931ea449f3d265/Dockerfile#L59

**Comment by waleedsheyyab** [comment]
I was using the wrong image 
I ran the right image but I have this error in the logs 
12:13:11.887Z ERROR elastalert: elasticsearch:  GET https://10.0.2.4:9200/elastalert_status/_search?size=1000 [status:400 request:0.063s]
12:13:11.887Z ERROR elastalert: elastalert:  Error finding recent pending alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [alert_time] in order to sort on') {'query': {'bool': {'must': {'query_string': {'query': '!_exists_:aggregate_id AND alert_sent:false'}}, 'filter': {'range': {'alert_time': {'from': '2022-01-16T12:13:11.802777Z', 'to': '2022-01-18T12:13:11.802812Z'}}}}}, 'sort': {'alert_time': {'order': 'asc'}}} Traceback (most recent call last):  File "/opt/elastalert/elastalert/elastalert.py", line 1740, in find_recent_pending_alerts  res = self.writeback_es.search(index=self.writeback_index, body=query, size=1000)  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/client/utils.py", line 84, in _wrapped  return func(*args, params=params, **kwargs)  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/client/__init__.py", line 810, in search  return self.transport.perform_request(  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/transport.py", line 318, in perform_request  status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/connection/http_requests.py", line 91, in perform_request  self._raise_error(response.status_code, raw_data)  File "/usr/lib/python3.9/site-packages/elasticsearch-7.0.0-py3.9.egg/elasticsearch/connection/base.py", line 131, in _raise_error  raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info) elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [alert_time] in order to sort on')


also the same error on the gui

**Comment by nsano-rururu** [comment]
It looks like I haven't set the TLS settings for elastalert2, elastalert2-server, and elastastalert-kibana-plugin, but I can't say anything because I don't know if the elastalert2-server and elastalert2 settings are set correctly.

**Comment by nsano-rururu** [comment]
■elastalert2-server
https://github.com/Karql/elastalert2-server
```json
  "es_ssl": true, // Enable/Disable SSL
  "ea_verify_certs": true, //  Verify TLS certificates. false for self-signed certificate
  "es_ca_certs": "/etc/ssl/elasticsearch/ca", // Path to ca for ElasticSearch (SSL must be enabled)
  "es_client_cert": "/etc/ssl/elasticsearch/cert", // Path to cert for ElasticSearch (SSL must be enabled)
  "es_client_key": "/etc/ssl/elasticsearch/key", // Path to key for ElasticSearch (SSL must be enabled)
```

■elastalert2
use_ssl
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#use-ssl
verify_certs
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#verify-certs
client-cert
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#client-cert
ca_certs
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#verify-certs

■ElastAlert Kibana Plugin
https://github.com/karql/elastalert-kibana-plugin#configuration
elastalertKibanaPlugin.serverSsl: true

**Comment by nsano-rururu** [comment]
I've never checked if elastalert-kibana-plugin works fine with SSL connection

**Comment by nsano-rururu** [comment]
Regarding the settings of elastalet-server and elastalert, the settings that I tried to connect with the SSL self-signed certificate at the link below may be helpful.
https://github.com/johnsusek/praeco/issues/236#issuecomment-680124949

**Comment by nsano-rururu** [comment]
Since elastalet-kibana-plugin cannot specify es_username and es_password when connecting to ssl, it may not work properly if es_username and es_password are specified. It's just a guess

**Comment by Karql** [comment]
> I've never checked if elastalert-kibana-plugin works fine with SSL connection

> Since elastalet-kibana-plugin cannot specify es_username and es_password when connecting to ssl, it may not work properly if es_username and es_password are specified. It's just a guess

`elastalert-kibana-plugin` makes api calls only to `elastalert2-server`.

IMO this is not SSL issue.

```
12:13:11.887Z ERROR elastalert: elastalert: Error finding recent pending alerts: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [alert_time] in order to sort on') {'query': {'bool': {'must': {'query_string': {'query': '!exists:aggregate_id AND alert_sent:false'}}, 'filter': {'range': {'alert_time': {'from': '2022-01-16T12:13:11.802777Z', 'to': '2022-01-18T12:13:11.802812Z'}}}}}, 'sort': {'alert_time': {'order': 'asc'}}} Traceback (most recent call last): File "/opt/elastalert/elastalert/elastalert.py", line 1740
```

With ssl problem there won't be 400 http status code.

`No mapping found for [alert_time] in order to sort on` 
I think something is wrong with your indexes.

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/1252

**Comment by nsano-rururu** [comment]
https://github.com/Yelp/elastalert/issues/1252#issuecomment-440768301
>From the documentation: "All documents must have a timestamp field. ElastAlert will try to use @timestamp by default, but this can be changed with the timestamp_field option"

**Comment by nsano-rururu** [comment]
https://elastalert2.readthedocs.io/en/latest/recipes/faq.html#i-m-not-using-timestamp-what-do-i-do

**Comment by waleedsheyyab** [comment]
still facing the same issue even though I added the time stamp in the rule , the service is running here are the logs : 
13:58:47.289Z  INFO elastalert-server: Server:  Websocket listening on port 3333
14:00:04.078Z  WARN elastalert: py.warnings:  /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.0.2.4'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings  warnings.warn(
14:00:04.078Z ERROR elastalert: py.warnings:  /usr/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.0.2.4'. Adding certificate verification is strongly advised. See: https://urllib3.

But the plugin isn't working I'm facing the same issue 

undefined - undefined
undefined is not an object (evaluating 'resp.rules.sort')

**Comment by nsano-rururu** [comment]
What are the ssl settings for elastalert2 and elastalert2-server?

**Comment by nsano-rururu** [comment]
https://elastalert2.readthedocs.io/en/latest/ruletypes.html#verify-certs

**Comment by nsano-rururu** [comment]
https://github.com/Karql/elastalert2-server#configuration

**Comment by waleedsheyyab** [comment]
I didn't install elastalert2 I only installed elastalert2-server image do I need elastalert2 ? 

in the config file : 
# Connect with TLS to Elasticsearch
use_ssl: True

# Verify TLS certificates
verify_certs: False

# GET request with body is the default option for Elasticsearch.
# If it fails for some reason, you can pass 'GET', 'POST' or 'source'.
# See http://elasticsearch-py.readthedocs.io/en/master/connection.html?highlight=send_get_body_as#transport
# for details
#es_send_get_body_as: GET

# Option basic-auth username and password for Elasticsearch
es_username: marsa
es_password: abc123

# Use SSL authentication with client certificates client_cert must be
# a pem file containing both cert and key for client
verify_certs: False
#ca_certs: /path/to/cacert.pem
#client_cert: /path/to/client_cert.pem
#client_key: /path/to/client_key.key

# The index on es_host which is used for metadata storage
# This can be a unmapped index, but it is recommended that you run
# elastalert-create-index to set a mapping
writeback_index: elastalert_status
writeback_alias: elastalert_alerts

**Comment by nsano-rururu** [comment]
elastalert2-server
https://github.com/Karql/elastalert2-server#configuration
```yaml
  "es_host": "localhost", // For getting metadata and field mappings, connect to this ES server
  "es_port": 9200, // Port for above
  "es_username": "", // Option basic-auth username and password for Elasticsearch
  "es_password": "", // Option basic-auth username and password for Elasticsearch
  "es_ssl": true, // Enable/Disable SSL
  "ea_verify_certs": true, //  Verify TLS certificates. false for self-signed certificate
  "es_ca_certs": "/etc/ssl/elasticsearch/ca", // Path to ca for ElasticSearch (SSL must be enabled)
  "es_client_cert": "/etc/ssl/elasticsearch/cert", // Path to cert for ElasticSearch (SSL must be enabled)
  "es_client_key": "/etc/ssl/elasticsearch/key", // Path to key for ElasticSearch (SSL must be enabled)
```

**Comment by nsano-rururu** [comment]
Is "10.0.2.4" an IP address that can be accessed from the docker container? .. It feels like a private IP address (local IP address). Do you have a?

**Comment by waleedsheyyab** [comment]
If It can't access the host the service won't be running , it's not ssl issue

**Comment by nsano-rururu** [comment]
good bye. You can solve it yourself, right?

**Comment by waleedsheyyab** [comment]
Professionalism at it's best, Thank you ,

**Comment by waleedsheyyab** [comment]
The guy was not friendly and not helpful , I have screenshots ,
