### ISSUE TITLE
When will there be a new version that supports Kibana 8.0.0

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#24]

**Comment by Karql** [comment]
When `elastalert2` will support `elasticsearch8` https://github.com/jertel/elastalert2/issues/92

**Comment by nsano-rururu** [comment]
look
https://github.com/jertel/elastalert2/issues/92#issuecomment-1037181046

**Comment by nsano-rururu** [comment]
Elastalert 2 2.4.0 for elasticsearch 8 has been released.
https://hub.docker.com/r/jertel/elastalert2/tags

**Comment by Karql** [comment]
Hi!

I've just added to release https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.4.1 😉

Regards

**Comment by nsano-rururu** [comment]
By the way, kibana: 8.1.0 has been released

**Comment by Karql** [comment]
I will release for it tomorrow.

**Comment by Karql** [comment]
Unfortunately not so easy. Some work has to be done.

https://github.com/Karql/elastalert-kibana-plugin/issues/27

I will do it when I will find some free time.

**Comment by Karql** [comment]
Done 😁

https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.4.2
