### ISSUE TITLE
Hi, Are there any plans to release Elastalert plugins for kibana 7.17.4?

### ISSUE THREAD

**Issue by ericliuk** [Karql/elastalert-kibana-plugin#29]
kibana-plugin works fine in kibana 7.17.3, but after I upgrade to 7.17.4 it doesn't display properly, is there any plan to release 7.17.4?

**Comment by Karql** [comment]
I have not released for version >= 7.17.2

![image](https://user-images.githubusercontent.com/173098/173793604-96f3ac9c-4660-4a9f-8a86-d69d6b9aa073.png)

I wonder how you used pluigin in 7.17.3. Have you built it yourself?

>  it doesn't display properly

Please provide more details.

**Comment by ericliuk** [comment]
Yes, I modified the kibanaVersion in 7.17.1 to 7.17.3 and it worked fine in kibana 7.17.3. After upgrading kibana to 7.17.4, just modifying kibanaVersion didn't work anymore, so I rebuild KibanaPlugin to generate elastalertKibanaPlugin-1.4.1-7.17.4.zip, but after installing it, it only shows that there is this plugin but not the specific rule.
![image](https://user-images.githubusercontent.com/67360695/173816797-ea258d1b-e709-456a-81b4-ee057ad9cb36.png)
![image](https://user-images.githubusercontent.com/67360695/173816839-d9c16348-03d8-4259-80f7-e784da6d0ba1.png)

**Comment by Karql** [comment]
https://github.com/Karql/elastalert-kibana-plugin/blob/1.4.1/CONTRIBUTING.md
You have done something wrong 😉

I've just released for versions:
- 7.17.2
- 7.17.3
- 7.17.4

https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.4.1

![image](https://user-images.githubusercontent.com/173098/173877541-d7594dfb-12b8-4bfe-995d-1198e8bc82a1.png)

**Comment by ericliuk** [comment]
@Karql It works fine. Thank you very, very much!

**Comment by Karql** [comment]
No problem 👌
