### ISSUE TITLE
Plugin installation was unsuccessful due to error "Plugin elastalertKibanaPlugin [8.4.0] is incompatible with Kibana [8.4.1]"

### ISSUE THREAD

**Issue by gentitope** [Karql/elastalert-kibana-plugin#31]
=> ERROR [2/3] RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.5.0/elastalertKibanaPlugin-1.5.0-8.4.0.zip                     3.3s
------                                                                                                                                                                                                    
 > [2/3] RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.5.0/elastalertKibanaPlugin-1.5.0-8.4.0.zip:                                
#5 2.426 Attempting to transfer from https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.5.0/elastalertKibanaPlugin-1.5.0-8.4.0.zip                                                     
#5 3.155 Transferring 49057 bytes....................                                                                                                                                                     
#5 3.181 Transfer complete                                                                                                                                                                                
#5 3.181 Retrieving metadata from plugin archive
#5 3.207 Extracting plugin archive
#5 3.245 Extraction complete
#5 3.267 Plugin installation was unsuccessful due to error "Plugin elastalertKibanaPlugin [8.4.0] is incompatible with Kibana [8.4.1]"
------
executor failed running [/bin/sh -c /usr/share/kibana/bin/kibana-plugin install https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.5.0/elastalertKibanaPlugin-1.5.0-8.4.0.zip]: exit code: 70

**Comment by Karql** [comment]
Please read: https://github.com/Karql/elastalert-kibana-plugin/issues/30#issuecomment-1219447280

**Comment by Karql** [comment]
Plugin for kibana `v8.4.1` released: https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.5.0/elastalertKibanaPlugin-1.5.0-8.4.1.zip
