### ISSUE TITLE
Add configuration for serverBasePath and serverRequestHeader 

### ISSUE THREAD

**Issue by anmoel** [Karql/elastalert-kibana-plugin#34]
Hi,

we split our frontend- and backend-systems and we want to host the elastalert2 server behind an api-gateway. 
This api-gateway hosts many APIs so we need a basePath option for selecting the elastalert server.
Additional we must add custom headers on each request, so we can authenticate against our api-gateway.

i will prepare a pull-request for both.

regards
André

**Comment by Karql** [comment]
Hi,

Why do you want to expose `elastalert2-server` with an api-gateway?
Only for elastalert-kibana-plugin or do you have another use case?

If only for plugin imo there is no such need.

Plugin does not make requests directly to `elastalert2-server` but first make request to kibana and kibana proxied it to elastalert2-server.

IMO you should expose only kibana and keep `elasticsearch` and `elastalert2-server` internally.

![elastic-stack](https://user-images.githubusercontent.com/173098/197256439-c2bc6e23-a00c-4082-ba59-02c8ded2e8a0.png)

This approach is more secure.

Best regards,
Mateusz

**Comment by anmoel** [comment]
hi.

kibana is an frontend application and not behind the api-gateway.
so the api-gateway is between the kibana server and the elastalert2-server and elasticsearch server

**Comment by Karql** [comment]
Is there something in front of kibana like `reverse-proxy`?

I don't see any reason why kibana it could not be behind `api-gateway`.

![elastic-stack2](https://user-images.githubusercontent.com/173098/197264093-86a6f2de-cb76-4ec8-818e-916aa5a12a53.png)

**Comment by anmoel** [comment]
the api gateway only supports REST conform APIs and not all HTTP requests. sessions and other http features are not supported

**Comment by Karql** [comment]
Released: https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.6.0
