### ISSUE TITLE
Kibana plugin banner

### ISSUE THREAD

**Issue by entisenat** [Karql/elastalert-kibana-plugin#36]
Hello guys,

Is there a way to install sort of info banner on ElastAlert page ?

Will explain:

We noticed that if somebody creates an alert without any configuration inside (just a name) - all alerting stops and sometime elastalert even crashes. So I would like to get people to pay attention to it.

Cheers.

**Comment by Karql** [comment]
Hi,

Banner is just a info that somebody can ignore.

It would be better to add validation but there is many cases that can go wrong e.g.
- like you said empty rules
- invalid yaml structure
- invalid rule
- and so one

I don't have plan to do that.

If you need this banner you could fork this repo, modify some html, build and use it ;)

Best regards,
Mateusz
