### ISSUE TITLE
Alert rules disappeared suddenly from kibana

### ISSUE THREAD

**Issue by gentitope** [Karql/elastalert-kibana-plugin#37]
Hello guys,

I noticed all the alert rules i created just disappeared after sometime suddenly.
As anyone face this before and if there is any explanation to it?

Cheers.

**Comment by Karql** [comment]
Hi!

Your problem is not related to `elastalert-kibana-plugin`.

Probably `elastalert2-server` or  directly to `elastalert2`.

I assume that you have made some misconfiguration like not assign volume for rules folder correctly.
