### ISSUE TITLE
incompatible with Kibana [7.10.0]

### ISSUE THREAD

**Issue by EsqerYasen** [Karql/elastalert-kibana-plugin#39]
talertKibanaPlugin-1.6.1-8.5.0.zip 
Attempting to transfer from file:///XXX/elastalertKibanaPlugin-1.6.1-8.5.0.zip
Transferring 49807 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Plugin elastalertKibanaPlugin [8.5.0] is incompatible with Kibana [7.10.0]"

**Comment by Karql** [comment]
You have downloaded version for kibana 8.5.0

You should use: https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.4.0/elastalertKibanaPlugin-1.4.0-7.10.0.zip

**Comment by EsqerYasen** [comment]
> You have downloaded version for kibana 8.5.0
> 
> You should use: https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.4.0/elastalertKibanaPlugin-1.4.0-7.10.0.zip

thanks ,that helps!
