### ISSUE TITLE
error on the kibana web page

### ISSUE THREAD

**Issue by xiehaibo1** [Karql/elastalert-kibana-plugin#41]
![5ba5a34c1afd3299dfb67cfd2f70cab](https://user-images.githubusercontent.com/126550531/222070356-7716d728-cf2f-465d-9695-806cdb5b12a9.png)

hi, I get this error on the web page,should I do something to start this elastalert server ?

**Comment by Karql** [comment]
Hi,

You can find everything you need in `README.md` https://github.com/Karql/elastalert2-server
There is also a sample configuration: https://github.com/Karql/elastalert-kibana-plugin/blob/master/dev/test-env/docker-compose.yml

Best regards,
Mateusz
