### ISSUE TITLE
Issue building plugin for 7.17.9

### ISSUE THREAD

**Issue by InvertedReality** [Karql/elastalert-kibana-plugin#42]
I'm having issues with attempting to build the plugin for version 7.17.9.  Any help is much appreciated.

$ yarn build --kibana-version=7.17.9
yarn run v1.22.19
$ yarn plugin-helpers build --kibana-version=7.17.9
$ node ../../scripts/plugin_helpers build --kibana-version=7.17.9
 info deleting the build and target directories
 info running @kbn/optimizer
 │ info initialized, 0 bundles cached
 │ info starting worker [1 bundle]
 │ERROR webpack compile errors
     │ERROR [elastalertKibanaPlugin] build
         │ERROR Optimizations failure.
         │         30 modules
         │
         │          ERROR in ./public/components/main/main.tsx
         │          Module not found: Error: Can't resolve '@kbn/i18n-react' in '/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/components/main'
         │          resolve '@kbn/i18n-react' in '/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/components/main'
         │            Parsed request is a module
         │            using description file: /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/package.json (relative path: ./public/components/main)
         │              Field 'browser' doesn't contain a valid alias configuration
         │              resolve as module
         │                /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/components/main/node_modules doesn't exist or is not a directory
         │                /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/components/node_modules doesn't exist or is not a directory
         │                /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/node_modules doesn't exist or is not a directory
         │                /Users/cody/Development/kibana/plugins/node_modules doesn't exist or is not a directory
         │                /Users/cody/Development/node_modules doesn't exist or is not a directory
         │                /Users/cody/node_modules doesn't exist or is not a directory
         │                /Users/node_modules doesn't exist or is not a directory
         │                /node_modules doesn't exist or is not a directory
         │                looking for modules in /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules
         │                  using description file: /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/package.json (relative path: ./node_modules)
         │                    Field 'browser' doesn't contain a valid alias configuration
         │                looking for modules in /Users/cody/Development/kibana/node_modules
         │                  using description file: /Users/cody/Development/kibana/package.json (relative path: ./node_modules)
         │                    Field 'browser' doesn't contain a valid alias configuration
         │                    using description file: /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/package.json (relative path: ./node_modules/@kbn/i18n-react)
         │                      no extension
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                    using description file: /Users/cody/Development/kibana/package.json (relative path: ./node_modules/@kbn/i18n-react)
         │                      no extension
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react doesn't exist
         │                      .js
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/node_modules/@kbn/i18n-react doesn't exist
         │                      .js
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.js doesn't exist
         │                      .ts
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/node_modules/@kbn/i18n-react.js doesn't exist
         │                      .ts
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.ts doesn't exist
         │                      .tsx
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/node_modules/@kbn/i18n-react.ts doesn't exist
         │                      .tsx
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.tsx doesn't exist
         │                      .json
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/node_modules/@kbn/i18n-react.tsx doesn't exist
         │                      .json
         │                        Field 'browser' doesn't contain a valid alias configuration
         │                        /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.json doesn't exist
         │                        /Users/cody/Development/kibana/node_modules/@kbn/i18n-react.json doesn't exist
         │                      as directory
         │                        /Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react doesn't exist
         │                      as directory
         │                        /Users/cody/Development/kibana/node_modules/@kbn/i18n-react doesn't exist
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/components/main/node_modules
{
  "name": "elastalert-kibana-plugin",
  "version": "1.6.1",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "elastalert-kibana-plugin",
      "version": "1.6.1",
      "license": "SEE LICENSE IN LICENSE.md",
      "dependencies": {
        "i18next": "^22.4.13",
        "react-i18next": "^12.2.0"
      }
    },
    "node_modules/@babel/runtime": {
      "version": "7.21.0",
      "resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.21.0.tgz",
      "integrity": "sha512-xwII0//EObnq89Ji5AKYQaRYiW/nZ3llSv29d49IuxPhKbtJoLP+9QUUZ4nVragQVtaVGeZrpB+ZtG/Pdy/POw==",
      "license": "MIT",
      "dependencies": {
        "regenerator-runtime": "^0.13.11"
      },
      "engines": {
        "node": ">=6.9.0"
      }
    },
    "node_modules/html-parse-stringify": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/html-parse-stringify/-/html-parse-stringify-3.0.1.tgz",
      "integrity": "sha512-KknJ50kTInJ7qIScF3jeaFRpMpE8/lfiTdzf/twXyPBLAGrLRTmkz3AdTnKeh40X8k9L2fdYwEp/42WGXIRGcg==",
      "license": "MIT",
      "dependencies": {
        "void-elements": "3.1.0"
      }
    },
    "node_modules/i18next": {
      "version": "22.4.13",
      "resolved": "https://registry.npmjs.org/i18next/-/i18next-22.4.13.tgz",
      "integrity": "sha512-GX7flMHRRqQA0I1yGLmaZ4Hwt1JfLqagk8QPDPZsqekbKtXsuIngSVWM/s3SLgNkrEXjA+0sMGNuOEkkmyqmWg==",
      "funding": [
        {
          "type": "individual",
          "url": "https://locize.com"
        },
        {
          "type": "individual",
          "url": "https://locize.com/i18next.html"
        },
        {
          "type": "individual",
          "url": "https://www.i18next.com/how-to/faq#i18next-is-awesome.-how-can-i-support-the-project"
        }
      ],
      "dependencies": {
        "@babel/runtime": "^7.20.6"
      }
    },
    "node_modules/js-tokens": {
      "version": "4.0.0",
      "resolved": "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz",
      "integrity": "sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==",
      "peer": true
    },
    "node_modules/loose-envify": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz",
      "integrity": "sha512-lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==",
      "peer": true,
      "dependencies": {
        "js-tokens": "^3.0.0 || ^4.0.0"
      },
      "bin": {
        "loose-envify": "cli.js"
      }
    },
    "node_modules/react": {
      "version": "18.2.0",
      "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
      "integrity": "sha512-/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==",
      "peer": true,
      "dependencies": {
        "loose-envify": "^1.1.0"
      },
      "engines": {
        "node": ">=0.10.0"
      }
    },
    "node_modules/react-i18next": {
      "version": "12.2.0",
      "resolved": "https://registry.npmjs.org/react-i18next/-/react-i18next-12.2.0.tgz",
      "integrity": "sha512-5XeVgSygaGfyFmDd2WcXvINRw2WEC1XviW1LXY/xLOEMzsCFRwKqfnHN+hUjla8ZipbVJR27GCMSuTr0BhBBBQ==",
      "dependencies": {
        "@babel/runtime": "^7.20.6",
        "html-parse-stringify": "^3.0.1"
      },
      "peerDependencies": {
        "i18next": ">= 19.0.0",
        "react": ">= 16.8.0"
      },
      "peerDependenciesMeta": {
        "react-dom": {
          "optional": true
        },
        "react-native": {
          "optional": true
        }
      }
    },
    "node_modules/regenerator-runtime": {
      "version": "0.13.11",
      "resolved": "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz",
      "integrity": "sha512-kY1AZVr2Ra+t+piVaJ4gxaFaReZVH40AKNo7UCX6W+dEwBo/2oZJzqfuN1qLq1oL45o56cPaTXELwrTh8Fpggg==",
      "license": "MIT"
    },
    "node_modules/void-elements": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/void-elements/-/void-elements-3.1.0.tgz",
]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/components/node_modules]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/public/node_modules]
         │          [/Users/cody/Development/kibana/plugins/node_modules]
         │          [/Users/cody/Development/node_modules]
         │          [/Users/cody/node_modules]
         │          [/Users/node_modules]
         │          [/node_modules]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react]
         │          [/Users/cody/Development/kibana/node_modules/@kbn/i18n-react]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.js]
         │          [/Users/cody/Development/kibana/node_modules/@kbn/i18n-react.js]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.ts]
         │          [/Users/cody/Development/kibana/node_modules/@kbn/i18n-react.ts]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.tsx]
         │          [/Users/cody/Development/kibana/node_modules/@kbn/i18n-react.tsx]
         │          [/Users/cody/Development/kibana/plugins/elastalert-kibana-plugin/node_modules/@kbn/i18n-react.json]
         │          [/Users/cody/Development/kibana/node_modules/@kbn/i18n-react.json]
         │           @ ./public/components/main/main.tsx 3:0-47 40:19-31
         │           @ ./public/components/main/index.ts
         │           @ ./public/application.tsx
         │           @ ./public/plugin.ts
         │           @ ./public/index.ts
         │           @ /Users/cody/Development/kibana/node_modules/@kbn/optimizer/target_node/worker/entry_point_creator.js
 │ERROR webpack issue
error Command failed with exit code 1.

**Comment by Karql** [comment]
Hi,

Sory I have prepared this version but forgot to upload...
Here is it: https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.4.1/elastalertKibanaPlugin-1.4.1-7.17.9.zip

btw. for 7.17.* you should use branch [`kibana7.17`](https://github.com/Karql/elastalert-kibana-plugin/tree/kibana7.17)

Best regards,
Mateusz
