### ISSUE TITLE
Kibana 8.7.0 support

### ISSUE THREAD

**Issue by ElPolito** [Karql/elastalert-kibana-plugin#43]
Hi!

Is there a plan to support Kibana 8.7.0?

Thanks!

**Comment by Karql** [comment]
Hi!

I have tried to build the plugin but there are some problems for this version 😔
I need some time to fix them.

Best regards,
Mateusz

**Comment by Karql** [comment]
https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.6.2

**Comment by ElPolito** [comment]
Great Thanks !
