### ISSUE TITLE
Challenges for elastalert-kibana-plugin 1.4.0

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#5]
- For 7.10.0, 7.10.1, 7.10.2 zip, please recreate the zip file referring to the following issue.
Also, please check the operation properly before releasing.

https://github.com/Karql/elastalert/issues/1
https://github.com/Karql/elastalert/issues/8

- Corresponding versions of 7.12.0, 7.12.1, 7.13.0, 7.13.1, 7.13.2, 7.13.3, 7.13.4 and 7.14.0 have not been released. You should be able to create it by referring to the following issue. Also, please check the operation properly before releasing. Even if you say you've released something that doesn't work, it's just garbage.

https://github.com/Karql/elastalert/issues/2
https://github.com/Karql/elastalert/issues/5
https://github.com/Karql/elastalert/issues/7

**Comment by Karql** [comment]
I have just released versions up to 7.14.0.

> Even if you say you've released something that doesn't work, it's just garbage.
Have you confirmed that it is not working or just saying so?

**Comment by nsano-rururu** [comment]
Please release it after confirming the operation.

**Comment by Karql** [comment]
I have checked every single version.
![image](https://user-images.githubusercontent.com/173098/130597955-56f88c39-c9bb-42d0-b9da-72cdfd58f9bf.png)

So why I am asking you if something not working for you.

**Comment by nsano-rururu** [comment]
I've answered the question. Why is it a question again? Are you stupid?

**Comment by nsano-rururu** [comment]
All you have to do is check the minimum operation. Don't you know that?
