### ISSUE TITLE
Help with unsupported version

### ISSUE THREAD

**Issue by shirser121** [Karql/elastalert-kibana-plugin#55]
I cant make it work for 8.15.5 if someout can help i would appriciat that!

**Comment by Karql** [comment]
Hi,

https://github.com/Karql/elastalert-kibana-plugin/releases/download/1.7.1/elastalertKibanaPlugin-1.7.1-8.15.5.zip

btw. In https://github.com/Karql/elastalert-kibana-plugin/blob/master/CONTRIBUTING.md is detailed instruciton how to build it.
