### ISSUE TITLE
Detect and respect "dark theme" Kibana

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#7]
https://github.com/bitsensor/elastalert-kibana-plugin/issues/124

**Comment by Karql** [comment]
Almost everything is ok:

![image](https://user-images.githubusercontent.com/173098/130563144-a61f19f8-b58e-4cf4-b0e2-92d6aa270de2.png)

![image](https://user-images.githubusercontent.com/173098/130563215-8efe878d-69f6-4753-800d-3ed4ca40f407.png)

Only editor needs some tweaks:
![image](https://user-images.githubusercontent.com/173098/130563259-505f9c59-8475-4bac-ae1a-fc2f4c3ada0f.png)

For nearest future I do not have plan to implement new features. 

Contribution is welcome 😉

**Comment by nsano-rururu** [comment]
It does not occur if it is a newly remade version. If so, no action is required. Close

**Comment by Karql** [comment]
Fixed:

![dark](https://user-images.githubusercontent.com/173098/157817234-addcb2e8-8445-487f-ab1d-1dbd203f2c36.png)
