### ISSUE TITLE
Templates cannot be selected yet

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#8]
https://github.com/bitsensor/elastalert-kibana-plugin/issues/56
https://github.com/bitsensor/elastalert-kibana-plugin/issues/71
https://github.com/bitsensor/elastalert-kibana-plugin/issues/142

**Comment by Karql** [comment]
> Official repository is not maintained anymore.
Aim of this fork is to support new versions of Kibana (after migration to Kibana New Platform starts from 7.10).

For nearest future I do not have plan to implement new features.

Contribution is welcome 😉
