### ISSUE TITLE
I feel that the rule test function is not working properly.

### ISSUE THREAD

**Issue by nsano-rururu** [Karql/elastalert-kibana-plugin#9]
Degradation has occurred.

**Comment by nsano-rururu** [comment]
It feels like the one released now is 1.4.0 beta 1 instead of 1.4.0.

**Comment by nsano-rururu** [comment]
Regarding this problem, it is a recognition that ch-bas recreated with the new kibana plugin is a problem that the original implementation ignored and implemented, not the problem of elastalert-server.

**Comment by nsano-rururu** [comment]
I moved the test button in kibana 7.16, but no response is returned. The movement is even more strange.
Looking at the kibana log, the http status is 400, so there may be a problem with the implementation when recreating with the new kibana-plugin.
If it is 400, it is a status code that is returned when the request parameter is insufficient or incomplete.
The cause is still unknown.


![a](https://user-images.githubusercontent.com/22293449/148755416-31d591dd-3427-4cc9-8d26-7017e64b1e33.PNG)


```yaml
{"type":"response","@timestamp":"2022-01-10T11:17:53+00:00","tags":[],"pid":7,"method":"post","statusCode":400,"req":{"url":"/api/elastalert/test","method":"post","headers":{"host":"localhost:5601","connection":"keep-alive","content-length":"938","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","kbn-version":"7.16.0","sec-ch-ua-platform":"\"Linux\"","accept":"*/*","origin":"http://localhost:5601","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:5601/app/elastAlert","accept-encoding":"gzip, deflate, br","accept-language":"ja,en-US;q=0.9,en;q=0.8"},"remoteAddress":"x.x.x.1","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","referer":"http://localhost:5601/app/elastAlert"},"res":{"statusCode":400,"responseTime":71,"contentLength":117},"message":"POST /api/elastalert/test 400 71ms - 117.0B"}
````

**Comment by Karql** [comment]
Do you remebmer how it works before migration to kibana new platform?

I think problem is in both `elastalert-kibana-pluing` (invalid request to api) and `elastalert2-server` (returns empty 204 respons when exception occurs). 

I have to investigate it carefully.

**Comment by nsano-rururu** [comment]
Before modifying to a new platform ( https://github.com/nsano-rururu/elastalert-kibana-plugin ) +
Move with ＋ kibana 7.9.3 and move when you press the test button
You can see something by looking at kibana's log.

**Comment by nsano-rururu** [comment]
kibana 7.9.3 + elastalert-kibana-plugin 1.3.0

kibana log
```sh
{"type":"response","@timestamp":"2022-01-12T17:01:27Z","tags":[],"pid":9,"method":"post","statusCode":200,"req":{"url":"/api/elastalert/test","method":"post","headers":{"host":"localhost:5601","connection":"keep-alive","content-length":"896","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","kbn-version":"7.9.3","sec-ch-ua-platform":"\"Linux\"","origin":"http://localhost:5601","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:5601/app/elastalert-kibana-plugin","accept-encoding":"gzip, deflate, br","accept-language":"ja,en-US;q=0.9,en;q=0.8"},"remoteAddress":"172.21.0.1","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","referer":"http://localhost:5601/app/elastalert-kibana-plugin"},"res":{"statusCode":200,"responseTime":34726,"contentLength":9},"message":"POST /api/elastalert/test 200 34726ms - 9.0B"}
```
![WS000000](https://user-images.githubusercontent.com/22293449/149187515-08c7c63f-2e4d-4d94-b58d-95c8d0f8f889.JPG)
![WS000001](https://user-images.githubusercontent.com/22293449/149187533-53098fa0-ffb7-4e04-a964-f48e4cf49203.JPG)

**Comment by Karql** [comment]
Thank you very much!

As I thought - plain output from `python -m elastalert.test_rule` is returned.

I will try to fix it 😉

**Comment by Filipp0vAP** [comment]
Hello!

I also ran into a problem when trying to test a rule from a plugin.
Tell me, please, is this the same problem as yours or something else?
When you click the "Test" button, the page becomes empty, and an error appears in the browser logs.
However, the server responds with 200. But the rule does not work out.
I appreciate any help, thank you!

Kibana 7.12.0 
![image](https://user-images.githubusercontent.com/38728938/150369817-214e43dd-84b5-49b5-ba58-e0876eaeb49f.png)

**Comment by Karql** [comment]
I've fixed this.

https://github.com/Karql/elastalert-kibana-plugin/releases/tag/1.4.1

(required [ElastAlert2 Server](https://github.com/Karql/elastalert2-server) in version >=5.0.0-next.4) 

Success:
![image](https://user-images.githubusercontent.com/173098/150387936-1b14550d-8810-4c5a-925b-75f4672f19fd.png)

Error:
![image](https://user-images.githubusercontent.com/173098/150388390-49be9668-2772-4a27-b508-1ab83cffce23.png)

@nsano-rururu  could you check it?

btw. I can see results on your screens.
![image](https://user-images.githubusercontent.com/173098/150388870-f00d4436-ecb5-4821-bbfc-5ae0ccd76fa3.png)

Original plugins works with `schemaOnly` mode. Have you changed something?

Now I've also changed to `all` mode.
https://github.com/Karql/elastalert-kibana-plugin/commit/877bdc1302d27518bf26ffc98c8ace046271a2b9#diff-efaccb9cc2b53e7a982d5b1b2ffedc73cac5ed7b0e51f2697776c59483a86e41R86

@Filipp0vAP

Yes this is the same issue. I've only release plugin for kibana `7.16.2`. If you need for older version please see for instruction in `Contribution.MD`

**Comment by nsano-rururu** [comment]
@Karql

what is it? .. I don't think it matters?
If it's kibana 7.12, I think it's the version you're guaranteed to work with.

**Comment by nsano-rururu** [comment]
@Karql

>Original plugins works with schemaOnly mode. Have you changed something?

Did nothing
It wasn't made by me in the first place.
I think it was implemented by bitsensor, but don't ask without checking.

**Comment by nsano-rururu** [comment]
The test button did not hide when the version did not work properly. I'll be asking similar questions in the future.

**Comment by nsano-rururu** [comment]
@Karql 

I think it's amazing that I fixed the bug and made it work

**Comment by nsano-rururu** [comment]
In the version before 1.4.1, I thought that I should have hidden the test button if it did not work properly. It's not the latest version.

**Comment by nsano-rururu** [comment]
No action is required. I just noticed it now.

**Comment by dianamelinte23** [comment]
> Yes this is the same issue. I've only release plugin for kibana `7.16.2`. If you need for older version please see for instruction in `Contribution.MD`

Hello! 
I've tried to build this plugin for 7.12.1 based on instruction in this file, but no success.

**Comment by Karql** [comment]
@dianamelinte23 maybe if you provided more information it would be easier to help - I don't have crystal ball 😅

Please: [elastalertKibanaPlugin-1.4.1-17.12.1.zip](https://github.com/Karql/elastalert-kibana-plugin/files/8952655/elastalertKibanaPlugin-1.4.1-17.12.1.zip)
